package com.xintong.maintain.cloudprovider.entity;

import java.math.BigDecimal;
import java.util.Date;

public class EduCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.teacher_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.subject_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.subject_parent_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String subjectParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.price
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.lesson_num
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Integer lessonNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.cover
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.buy_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Long buyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.view_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.version
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.status
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_course.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.id
     *
     * @return the value of edu_course.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.id
     *
     * @param id the value for edu_course.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.teacher_id
     *
     * @return the value of edu_course.teacher_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.teacher_id
     *
     * @param teacherId the value for edu_course.teacher_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.subject_id
     *
     * @return the value of edu_course.subject_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.subject_id
     *
     * @param subjectId the value for edu_course.subject_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.subject_parent_id
     *
     * @return the value of edu_course.subject_parent_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getSubjectParentId() {
        return subjectParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.subject_parent_id
     *
     * @param subjectParentId the value for edu_course.subject_parent_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setSubjectParentId(String subjectParentId) {
        this.subjectParentId = subjectParentId == null ? null : subjectParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.title
     *
     * @return the value of edu_course.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.title
     *
     * @param title the value for edu_course.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.price
     *
     * @return the value of edu_course.price
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.price
     *
     * @param price the value for edu_course.price
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.lesson_num
     *
     * @return the value of edu_course.lesson_num
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Integer getLessonNum() {
        return lessonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.lesson_num
     *
     * @param lessonNum the value for edu_course.lesson_num
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setLessonNum(Integer lessonNum) {
        this.lessonNum = lessonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.cover
     *
     * @return the value of edu_course.cover
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.cover
     *
     * @param cover the value for edu_course.cover
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.buy_count
     *
     * @return the value of edu_course.buy_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Long getBuyCount() {
        return buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.buy_count
     *
     * @param buyCount the value for edu_course.buy_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setBuyCount(Long buyCount) {
        this.buyCount = buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.view_count
     *
     * @return the value of edu_course.view_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.view_count
     *
     * @param viewCount the value for edu_course.view_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.version
     *
     * @return the value of edu_course.version
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.version
     *
     * @param version the value for edu_course.version
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.status
     *
     * @return the value of edu_course.status
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.status
     *
     * @param status the value for edu_course.status
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.gmt_create
     *
     * @return the value of edu_course.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.gmt_create
     *
     * @param gmtCreate the value for edu_course.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_course.gmt_modified
     *
     * @return the value of edu_course.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_course.gmt_modified
     *
     * @param gmtModified the value for edu_course.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}