package com.xintong.maintain.cloudprovider.entity;

import java.util.Date;

public class EduChapter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_chapter.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_chapter.course_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_chapter.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_chapter.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_chapter.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_chapter.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_chapter.id
     *
     * @return the value of edu_chapter.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_chapter.id
     *
     * @param id the value for edu_chapter.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_chapter.course_id
     *
     * @return the value of edu_chapter.course_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_chapter.course_id
     *
     * @param courseId the value for edu_chapter.course_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_chapter.title
     *
     * @return the value of edu_chapter.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_chapter.title
     *
     * @param title the value for edu_chapter.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_chapter.sort
     *
     * @return the value of edu_chapter.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_chapter.sort
     *
     * @param sort the value for edu_chapter.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_chapter.gmt_create
     *
     * @return the value of edu_chapter.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_chapter.gmt_create
     *
     * @param gmtCreate the value for edu_chapter.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_chapter.gmt_modified
     *
     * @return the value of edu_chapter.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_chapter.gmt_modified
     *
     * @param gmtModified the value for edu_chapter.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}