package com.xintong.maintain.cloudprovider.entity;

import java.util.Date;

public class EduTeacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.name
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.intro
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.level
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.avatar
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.is_deleted
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.career
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String career;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.id
     *
     * @return the value of edu_teacher.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.id
     *
     * @param id the value for edu_teacher.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.name
     *
     * @return the value of edu_teacher.name
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.name
     *
     * @param name the value for edu_teacher.name
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.intro
     *
     * @return the value of edu_teacher.intro
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.intro
     *
     * @param intro the value for edu_teacher.intro
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.level
     *
     * @return the value of edu_teacher.level
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.level
     *
     * @param level the value for edu_teacher.level
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.avatar
     *
     * @return the value of edu_teacher.avatar
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.avatar
     *
     * @param avatar the value for edu_teacher.avatar
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.sort
     *
     * @return the value of edu_teacher.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.sort
     *
     * @param sort the value for edu_teacher.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.is_deleted
     *
     * @return the value of edu_teacher.is_deleted
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.is_deleted
     *
     * @param isDeleted the value for edu_teacher.is_deleted
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.gmt_create
     *
     * @return the value of edu_teacher.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.gmt_create
     *
     * @param gmtCreate the value for edu_teacher.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.gmt_modified
     *
     * @return the value of edu_teacher.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.gmt_modified
     *
     * @param gmtModified the value for edu_teacher.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.career
     *
     * @return the value of edu_teacher.career
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.career
     *
     * @param career the value for edu_teacher.career
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setCareer(String career) {
        this.career = career == null ? null : career.trim();
    }
}