package com.xintong.maintain.cloudprovider.entity;

import java.util.Date;

public class EduVideo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.course_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.chapter_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.video_source_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String videoSourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.video_original_name
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String videoOriginalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.play_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Long playCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.is_free
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Byte isFree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.duration
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Float duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.status
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.size
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.version
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_video.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.id
     *
     * @return the value of edu_video.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.id
     *
     * @param id the value for edu_video.id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.course_id
     *
     * @return the value of edu_video.course_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.course_id
     *
     * @param courseId the value for edu_video.course_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.chapter_id
     *
     * @return the value of edu_video.chapter_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.chapter_id
     *
     * @param chapterId the value for edu_video.chapter_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId == null ? null : chapterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.title
     *
     * @return the value of edu_video.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.title
     *
     * @param title the value for edu_video.title
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.video_source_id
     *
     * @return the value of edu_video.video_source_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getVideoSourceId() {
        return videoSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.video_source_id
     *
     * @param videoSourceId the value for edu_video.video_source_id
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setVideoSourceId(String videoSourceId) {
        this.videoSourceId = videoSourceId == null ? null : videoSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.video_original_name
     *
     * @return the value of edu_video.video_original_name
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getVideoOriginalName() {
        return videoOriginalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.video_original_name
     *
     * @param videoOriginalName the value for edu_video.video_original_name
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setVideoOriginalName(String videoOriginalName) {
        this.videoOriginalName = videoOriginalName == null ? null : videoOriginalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.sort
     *
     * @return the value of edu_video.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.sort
     *
     * @param sort the value for edu_video.sort
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.play_count
     *
     * @return the value of edu_video.play_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Long getPlayCount() {
        return playCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.play_count
     *
     * @param playCount the value for edu_video.play_count
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setPlayCount(Long playCount) {
        this.playCount = playCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.is_free
     *
     * @return the value of edu_video.is_free
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Byte getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.is_free
     *
     * @param isFree the value for edu_video.is_free
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setIsFree(Byte isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.duration
     *
     * @return the value of edu_video.duration
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Float getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.duration
     *
     * @param duration the value for edu_video.duration
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setDuration(Float duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.status
     *
     * @return the value of edu_video.status
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.status
     *
     * @param status the value for edu_video.status
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.size
     *
     * @return the value of edu_video.size
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.size
     *
     * @param size the value for edu_video.size
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.version
     *
     * @return the value of edu_video.version
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.version
     *
     * @param version the value for edu_video.version
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.gmt_create
     *
     * @return the value of edu_video.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.gmt_create
     *
     * @param gmtCreate the value for edu_video.gmt_create
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_video.gmt_modified
     *
     * @return the value of edu_video.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_video.gmt_modified
     *
     * @param gmtModified the value for edu_video.gmt_modified
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}