package com.xintong.maintain.cloudprovider.mapper;

import com.xintong.maintain.cloudprovider.entity.EduChapter;
import com.xintong.maintain.cloudprovider.entity.EduChapterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    long countByExample(EduChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByExample(EduChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insert(EduChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insertSelective(EduChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    List<EduChapter> selectByExample(EduChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    EduChapter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") EduChapter record, @Param("example") EduChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExample(@Param("record") EduChapter record, @Param("example") EduChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKeySelective(EduChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_chapter
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKey(EduChapter record);
}