package com.xintong.maintain.cloudprovider.mapper;

import com.xintong.maintain.cloudprovider.entity.EduCourse;
import com.xintong.maintain.cloudprovider.entity.EduCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    long countByExample(EduCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByExample(EduCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insert(EduCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insertSelective(EduCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    List<EduCourse> selectByExample(EduCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    EduCourse selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") EduCourse record, @Param("example") EduCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExample(@Param("record") EduCourse record, @Param("example") EduCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKeySelective(EduCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKey(EduCourse record);
}