package com.xintong.maintain.cloudprovider.mapper;

import com.xintong.maintain.cloudprovider.entity.EduCourseDescription;
import com.xintong.maintain.cloudprovider.entity.EduCourseDescriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduCourseDescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    long countByExample(EduCourseDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByExample(EduCourseDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insert(EduCourseDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insertSelective(EduCourseDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    List<EduCourseDescription> selectByExampleWithBLOBs(EduCourseDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    List<EduCourseDescription> selectByExample(EduCourseDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    EduCourseDescription selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") EduCourseDescription record, @Param("example") EduCourseDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") EduCourseDescription record, @Param("example") EduCourseDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExample(@Param("record") EduCourseDescription record, @Param("example") EduCourseDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKeySelective(EduCourseDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(EduCourseDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_course_description
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKey(EduCourseDescription record);
}