package com.xintong.maintain.cloudprovider.mapper;

import com.xintong.maintain.cloudprovider.entity.EduSubject;
import com.xintong.maintain.cloudprovider.entity.EduSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EduSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    long countByExample(EduSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByExample(EduSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insert(EduSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int insertSelective(EduSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    List<EduSubject> selectByExample(EduSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    EduSubject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") EduSubject record, @Param("example") EduSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByExample(@Param("record") EduSubject record, @Param("example") EduSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKeySelective(EduSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_subject
     *
     * @mbg.generated Sun May 17 11:19:16 CST 2020
     */
    int updateByPrimaryKey(EduSubject record);
}